dataset:
  root: data/mode_decomp_eval_dataset_v1/scalar_rect
  mask_policy: allow_none
task: pipeline
pipeline:
  decomposer: pod_svd
  coeff_post: pca
  model: ridge
output:
  root: runs
  name: scalar_rect_pod_pca
seed: 123
params:
  decompose:
    name: pod_svd
    mask_policy: ignore_masked_points
  model:
    target_space: z
