dataset:
  root: data/mode_decomp_eval_dataset_v1/scalar_rect
  mask_policy: allow_none
task: pipeline
pipeline:
  decomposer: fft2
  codec: fft_complex_codec_v1
  coeff_post: none
  model: ridge
output:
  root: runs
  name: scalar_rect_fft2
seed: 123
params:
  decompose:
    name: fft2
    disk_policy: error
