dataset:
  root: data/mode_decomp_eval_dataset_v1/scalar_disk
  mask_policy: allow_none
task: pipeline
pipeline:
  decomposer: zernike
  coeff_post: none
  model: ridge
output:
  root: runs
  name: scalar_disk_zernike
seed: 123
params:
  decompose:
    name: zernike
    n_max: 6
    ordering: n_then_m
    normalization: orthonormal
    boundary_condition: unit_disk
