dataset: data/mode_decomp_eval_dataset_v1/scalar_disk
task: train
pipeline:
  decomposer: zernike
  coeff_post: pca
  model: mtgp
output:
  root: runs
  tag: scalar_disk_zernike_pca_mtgp
  project: scalar_disk_zernike_pca_mtgp
seed: 123
params:
  domain:
    name: disk
    center:
    - 0.0
    - 0.0
    radius: 1.0
    x_range:
    - -1.0
    - 1.0
    y_range:
    - -1.0
    - 1.0
  decompose:
    name: zernike
    n_max: 6
    ordering: n_then_m
    normalization: orthonormal
    boundary_condition: unit_disk
  coeff_post:
    n_components: 8
  model:
    training_iter: 30
